style = ["config/global/style/blogstyle.css"]

head = ["config/global/elements/head.html", "config/global/elements/bloghead.html"]
[main]

[[main.block]]
from_str = "config/global/elements/navbar.html"
style = "html"

[[main.block]]
text = "<section>Blog</section>"
style = "html"
