style = ["config/global/style/blogstyle.css"]

head = ["config/global/elements/head.html"]
[main]

[[main.block]]
from_str = "config/global/elements/navbar.html"
style = "html"

[[main.block]]
style = "md"
text = "<img id='banner' src='../assets/changelog_banner.svg' />"
